### ISSUE TITLE
Suggestions for minor improvements

### ISSUE THREAD

**Issue by LaumiH** [SirToffski/Arch-GNS3-Helper#2]
Hi there,

amazing script, really saved me a ton of time!

One suggestion, however I have not investigated further if it is only a problem on Manjaro or Python 3.8: 
`python-pypi2pkgbuild` throws a strange `KeyError: 'CFLAGS'` error, which can be resolved by simply replacing it with `python-pypi2pkgbuild-git`.

Also, the most recent version now is 2.2.7 :)

Thank you again for the nice article and help, really appreciated!

**Comment by LaumiH** [comment]
Another thing ... In the function `install_vpcs()`, `check_for_vpcs=$(type vpcs | grep -c "vpcs is /usr/bin/vpcs")` does not work for me an gives 0 no matter if vpcs is installed or not.
I replaced it with `  if ! [[ -f "/usr/bin/vpcs" ]]; then`.

**Comment by SirToffski** [comment]
Hey thanks! Awesome suggestions - I shall update the script during my days off.

Cheers!

Edit: saw your PR, will review and merge ASAP 😊

**Comment by SirToffski** [comment]
Reviewed and merged your PR. Sorry it took a while, was slacking a bit...

Great work, thanks!
